/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum ActionType implements org.apache.avro.generic.GenericEnumSymbol<ActionType> {
  LOGIN, LOGOUT, PURCHASE, PAGE_VIEW, SEARCH, CART_ADD, CART_REMOVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActionType\",\"namespace\":\"com.training.kafka.avro\",\"symbols\":[\"LOGIN\",\"LOGOUT\",\"PURCHASE\",\"PAGE_VIEW\",\"SEARCH\",\"CART_ADD\",\"CART_REMOVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
