/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5258928408339198721L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceInfo\",\"namespace\":\"com.training.kafka.avro\",\"fields\":[{\"name\":\"deviceType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userAgent\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ipAddress\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"location\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeviceInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String deviceType;
  private java.lang.String userAgent;
  private java.lang.String ipAddress;
  private java.lang.String location;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceInfo() {}

  /**
   * All-args constructor.
   * @param deviceType The new value for deviceType
   * @param userAgent The new value for userAgent
   * @param ipAddress The new value for ipAddress
   * @param location The new value for location
   */
  public DeviceInfo(java.lang.String deviceType, java.lang.String userAgent, java.lang.String ipAddress, java.lang.String location) {
    this.deviceType = deviceType;
    this.userAgent = userAgent;
    this.ipAddress = ipAddress;
    this.location = location;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceType;
    case 1: return userAgent;
    case 2: return ipAddress;
    case 3: return location;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceType = value$ != null ? value$.toString() : null; break;
    case 1: userAgent = value$ != null ? value$.toString() : null; break;
    case 2: ipAddress = value$ != null ? value$.toString() : null; break;
    case 3: location = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deviceType' field.
   * @return The value of the 'deviceType' field.
   */
  public java.lang.String getDeviceType() {
    return deviceType;
  }


  /**
   * Sets the value of the 'deviceType' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.String value) {
    this.deviceType = value;
  }

  /**
   * Gets the value of the 'userAgent' field.
   * @return The value of the 'userAgent' field.
   */
  public java.lang.String getUserAgent() {
    return userAgent;
  }


  /**
   * Sets the value of the 'userAgent' field.
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.String value) {
    this.userAgent = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.String value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.String getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.String value) {
    this.location = value;
  }

  /**
   * Creates a new DeviceInfo RecordBuilder.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.training.kafka.avro.DeviceInfo.Builder newBuilder() {
    return new com.training.kafka.avro.DeviceInfo.Builder();
  }

  /**
   * Creates a new DeviceInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.training.kafka.avro.DeviceInfo.Builder newBuilder(com.training.kafka.avro.DeviceInfo.Builder other) {
    if (other == null) {
      return new com.training.kafka.avro.DeviceInfo.Builder();
    } else {
      return new com.training.kafka.avro.DeviceInfo.Builder(other);
    }
  }

  /**
   * Creates a new DeviceInfo RecordBuilder by copying an existing DeviceInfo instance.
   * @param other The existing instance to copy.
   * @return A new DeviceInfo RecordBuilder
   */
  public static com.training.kafka.avro.DeviceInfo.Builder newBuilder(com.training.kafka.avro.DeviceInfo other) {
    if (other == null) {
      return new com.training.kafka.avro.DeviceInfo.Builder();
    } else {
      return new com.training.kafka.avro.DeviceInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceInfo>
    implements org.apache.avro.data.RecordBuilder<DeviceInfo> {

    private java.lang.String deviceType;
    private java.lang.String userAgent;
    private java.lang.String ipAddress;
    private java.lang.String location;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.training.kafka.avro.DeviceInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[0].schema(), other.deviceType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[1].schema(), other.userAgent);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[2].schema(), other.ipAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.location)) {
        this.location = data().deepCopy(fields()[3].schema(), other.location);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.training.kafka.avro.DeviceInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[0].schema(), other.deviceType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[1].schema(), other.userAgent);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[2].schema(), other.ipAddress);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.location)) {
        this.location = data().deepCopy(fields()[3].schema(), other.location);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'deviceType' field.
      * @return The value.
      */
    public java.lang.String getDeviceType() {
      return deviceType;
    }


    /**
      * Sets the value of the 'deviceType' field.
      * @param value The value of 'deviceType'.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder setDeviceType(java.lang.String value) {
      validate(fields()[0], value);
      this.deviceType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceType' field has been set.
      * @return True if the 'deviceType' field has been set, false otherwise.
      */
    public boolean hasDeviceType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceType' field.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder clearDeviceType() {
      deviceType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userAgent' field.
      * @return The value.
      */
    public java.lang.String getUserAgent() {
      return userAgent;
    }


    /**
      * Sets the value of the 'userAgent' field.
      * @param value The value of 'userAgent'.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder setUserAgent(java.lang.String value) {
      validate(fields()[1], value);
      this.userAgent = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userAgent' field has been set.
      * @return True if the 'userAgent' field has been set, false otherwise.
      */
    public boolean hasUserAgent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userAgent' field.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder clearUserAgent() {
      userAgent = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public java.lang.String getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder setIpAddress(java.lang.String value) {
      validate(fields()[2], value);
      this.ipAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.String getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder setLocation(java.lang.String value) {
      validate(fields()[3], value);
      this.location = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.training.kafka.avro.DeviceInfo.Builder clearLocation() {
      location = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceInfo build() {
      try {
        DeviceInfo record = new DeviceInfo();
        record.deviceType = fieldSetFlags()[0] ? this.deviceType : (java.lang.String) defaultValue(fields()[0]);
        record.userAgent = fieldSetFlags()[1] ? this.userAgent : (java.lang.String) defaultValue(fields()[1]);
        record.ipAddress = fieldSetFlags()[2] ? this.ipAddress : (java.lang.String) defaultValue(fields()[2]);
        record.location = fieldSetFlags()[3] ? this.location : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceInfo>
    READER$ = (org.apache.avro.io.DatumReader<DeviceInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.deviceType);

    out.writeString(this.userAgent);

    out.writeString(this.ipAddress);

    if (this.location == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.location);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.deviceType = in.readString();

      this.userAgent = in.readString();

      this.ipAddress = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.location = null;
      } else {
        this.location = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.deviceType = in.readString();
          break;

        case 1:
          this.userAgent = in.readString();
          break;

        case 2:
          this.ipAddress = in.readString();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.location = null;
          } else {
            this.location = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










